FROM sphere-build

#MAINTAINER Dan Gershony - CoinVault <dan@coinvault.io>

RUN  mkdir /root/.stratis/

#COPY sphere.conf /root/.stratis/

VOLUME /root/.stratis

WORKDIR /usr/src/app/source/src/SphereD

